### ISSUE TITLE
Fix Codecov configuration with the new repository name

### ISSUE THREAD

**Issue by chiraganand** [xKDR/TimeFrames.jl#113]
Codecov cannot find the new repository name maybe it needs to be registered separately or somehow renamed on the Codecov website.

**Comment by chiraganand** [comment]
Refs #66 #111

**Comment by codetalker7** [comment]
@chiraganand this seems to have been resolved now.

**Comment by chiraganand** [comment]
> @chiraganand this seems to have been resolved now. Also, the coverage seems to be still the same as we had before. Not sure why it was showing the decrease.

Yes, working but I can still see `TS.jl` and `TSx.jl` in the coverage file list which is strange.

**Comment by chiraganand** [comment]
This is working now, closing.
